---
version: '3'

includes:
  rancher: https://raw.githubusercontent.com/standardloop/taskfiles/refs/tags/v0.0.1/rancher.yml
  color: https://raw.githubusercontent.com/standardloop/taskfiles/refs/tags/v0.0.1/color.yml

tasks:
  default:
    aliases: [all]
    silent: true
    deps:
      - color

  clean:
    deps:
      - rancher:clean
